config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root  'posts#index'
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources  :posts do
      resources :comments
    end
  end
  
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end
  
  
  
  before_action :set_locale
  def set_locale
    I18n.locale=params[:locale]||I18n.default_locale
  end
  
   def default_url_options (options={})
    {locale: I18n.locale}
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
   @comment = @post.comments.build(comment_params)    
   @comment.user= current_user
   format.js
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_post
      @post=Post.find(params[:post_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :kontrol]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :kontrol, only: [:edit, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
    
    def kontrol
      unless @post.user==current_user
      redirect_to posts_path, notice:"Yetkiniz Yok!"
      unless current_user==@post.user
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_field :bdy, id: :comment_bdy, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-3">
  <div class="actions">
    <%= f.submit "Yorum At", class:"form-action btn btn-info"  %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em><b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mucahit's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>
<%= yield %>
<%= render 'shared/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart:true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>

<div class="panel panel-default widget">
  
    <div class="form-group">
     <%= t('foto') %><br>
    <%=f.file_field :image, class:"form-control" %>
  </div>

  <div class="form-group ">
    <%= t('basliklar') %><br>
    <%= f.text_area :title, class:"form-control" %>
  </div>
  <div class="form-group ">
   <%= t('mesajlar') %><br>
    <%= f.text_area :msg, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"form-control btn btn-success"%>
  </div>
 
<% end %>

 </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
        <div class="row">
          <% @posts.each do |post| %>
 <div class="container">
      
                   
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item" style="box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5); padding: 5px;">
                            <div class="row">
                                <div class="hidden-xs col-md-1">
                                 <%=image_tag post.user.image.url(:mini) if post.user.image?%>
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                             <a href="?user=<%=post.user.id%>"> <%=post.user.name%> </a>  
                                             <div align="right"> <mark <i><%=t('postg')%>: <%=post.created_at%></i></mark> </div>
                                        </div>
                                    </div>
                                   <hr>

                                    <div class="comment-text">
                                        <mark><i><%=t('postb')%></i></mark> 
                                       <b> <%=post.title%> </b> <br/> <br>
                                       <div align ="center" id="rootimage"> <%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%> </div>
                                        <br/>
                                        <mark><i><%=t('postm')%></i></mark>
                                        <%=post.msg%>
                                    </div>
                                	
                                    <hr>
                                    <div class="action">
                                      <%= link_to t('sil'), post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>  &nbsp; &nbsp;
                                     <%= link_to t('duzenle'), edit_post_path(post),class:"glyphicon glyphicon-pencil" %>  &nbsp; &nbsp;
                                      <%= link_to t('goruntule'), post_path(post),class:"glyphicon glyphicon-hand-right" %>  <br>
          
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
            </div>
        </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel-body">
        <ul class="list-group" >
            <li class="list-group-item" style="box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5); padding: 5px;">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                       <%=image_tag @post.user.image.url(:mini) if @post.user.image?%> 
                    </div>
                    <div class="col-xs-10 col-md-11">
                        <div>
                            <div class="mic-info">
                                 <a href="?user=<%=@post.user.id%>"> <%=@post.user.name%> </a> 
                                  <div align="right"> <mark><i><%=t('postg')%>: <%=@post.created_at%></i></mark></div>
                            </div>
                        </div>
                            <hr>
                        
                        <div class="comment-text">
                             <mark><i><%=t('postb')%></i></i></mark>
                             
                           <b> <%=@post.title%> </b> <br/> <br>
                            <div align="center" id="rootimage"><%=image_tag @post.image.url(:medium),class:"img img-responsive" if @post.image?%> </div>
                            <br/> 
                             <mark><i><%=t('postm')%></i></mark>
                            <%=@post.msg%>
                            
                        </div>
                          
                        <hr>
                        <div class="action">
                       
                         <%= link_to t('sil'), @post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %> &nbsp; &nbsp;
                          <%= link_to t('duzenle'), edit_post_path(@post),class:"glyphicon glyphicon-pencil" %> <br>
                         
                          <hr>
                        </div>
                         <hr>
                    <div style="box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5); padding: 5px;"> 
                       <%=render 'comments/form'%>
                      <div id="comments" style="box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5); padding: 5px;">
                    
                      <%@comments.each do |c|%>
                      
                      <%=image_tag c.user.image.url(:mini) if c.user.image?%> <em> 
                     <<%=c.user.name%> </em> <b><%=c.bdy%> </b>    <br/>
                     <%end%> <br>
                     </div>
                      </div>
                      </div>
                    </div>
                  </div>
            </li>
        </ul>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
<footer id="foot">
  <h4 align="left"><b>Mücait KARABACAK - 14542511</b> </h4>
  <h4 align="left"><i><%=t("footer")%></i></h4>
  <center><% request.env.each do |key, value| %>
<strong><%= key %></strong> => <%= value %><br/>
<% end %></center>
</footer></div>

app/views/shared/_navbar.html.erb
<div class="container">
    <header id="head">
<nav class="navbar navbar-inverse" >
    <div class="navbar-header">
    <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
    </button>
     </div>
     <div class="collapse navbar-collapse" id="menu" >
    <ul class="nav navbar-nav"  >
    <% if user_signed_in?%>
    <li><%= link_to t('anasayfa'), posts_path%> </li>
	    <li><%= link_to t('yeniyazi'), new_post_path %></li>
	    <li><%= link_to t('duzenleprofil'), edit_user_registration_path, :class=>'navbar-link'%> </li>
    <li><%= link_to t('cikis'), destroy_user_session_path, method: :delete, :class=>'navbar-link'%> </li>
	    <% else %>
    <li><%= link_to t('anasayfa'), posts_path%></li>
	    <li><%= link_to t('kayit'), new_user_registration_path, :class => 'navbar-link' %> </li>
	    <li> <%= link_to t('girisyap'), new_user_session_path, :class => 'navbar-link' %></li>
    <%end%>
    </ul>
    </div>
</nav>
    <div align="right">
        
        Dil seçimi:
    <%= link_to_unless_current "İngilizce", locale: "en" %>   |  
    <%= link_to_unless_current "Türkçe", locale: "tr" %>
    </div>
</header>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid" align="center">
    <br>
    <h3 align="center" >
    </h3>
    <br>
</div>